#############################################################################
# Makefile for building: tabletReader
# Generated by qmake (2.01a) (Qt 4.7.2) on: Mon Jun 13 21:05:01 2011
# Project:  tabletReader.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile tabletReader.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/poppler/qt4 -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/lib -lpoppler-qt4 -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = documentwidget.cpp \
		main.cpp \
		window.cpp \
		SlidingStackedWidget.cpp \
		loadpages.cpp \
		filebrowser.cpp moc_documentwidget.cpp \
		moc_window.cpp \
		moc_SlidingStackedWidget.cpp \
		moc_loadpages.cpp \
		moc_filebrowser.cpp
OBJECTS       = documentwidget.o \
		main.o \
		window.o \
		SlidingStackedWidget.o \
		loadpages.o \
		filebrowser.o \
		moc_documentwidget.o \
		moc_window.o \
		moc_SlidingStackedWidget.o \
		moc_loadpages.o \
		moc_filebrowser.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		tabletReader.pro
QMAKE_TARGET  = tabletReader
DESTDIR       = 
TARGET        = tabletReader

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tabletReader.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile tabletReader.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile tabletReader.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/tabletReader1.0.0 || $(MKDIR) .tmp/tabletReader1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/tabletReader1.0.0/ && $(COPY_FILE) --parents documentwidget.h window.h SlidingStackedWidget.h loadpages.h filebrowser.h .tmp/tabletReader1.0.0/ && $(COPY_FILE) --parents documentwidget.cpp main.cpp window.cpp SlidingStackedWidget.cpp loadpages.cpp filebrowser.cpp .tmp/tabletReader1.0.0/ && (cd `dirname .tmp/tabletReader1.0.0` && $(TAR) tabletReader1.0.0.tar tabletReader1.0.0 && $(COMPRESS) tabletReader1.0.0.tar) && $(MOVE) `dirname .tmp/tabletReader1.0.0`/tabletReader1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/tabletReader1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_documentwidget.cpp moc_window.cpp moc_SlidingStackedWidget.cpp moc_loadpages.cpp moc_filebrowser.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_documentwidget.cpp moc_window.cpp moc_SlidingStackedWidget.cpp moc_loadpages.cpp moc_filebrowser.cpp
moc_documentwidget.cpp: documentwidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) documentwidget.h -o moc_documentwidget.cpp

moc_window.cpp: documentwidget.h \
		loadpages.h \
		window.h
	/usr/bin/moc $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

moc_SlidingStackedWidget.cpp: SlidingStackedWidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) SlidingStackedWidget.h -o moc_SlidingStackedWidget.cpp

moc_loadpages.cpp: loadpages.h
	/usr/bin/moc $(DEFINES) $(INCPATH) loadpages.h -o moc_loadpages.cpp

moc_filebrowser.cpp: filebrowser.h
	/usr/bin/moc $(DEFINES) $(INCPATH) filebrowser.h -o moc_filebrowser.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

documentwidget.o: documentwidget.cpp documentwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o documentwidget.o documentwidget.cpp

main.o: main.cpp window.h \
		documentwidget.h \
		loadpages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

window.o: window.cpp window.h \
		documentwidget.h \
		loadpages.h \
		SlidingStackedWidget.h \
		filebrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

SlidingStackedWidget.o: SlidingStackedWidget.cpp SlidingStackedWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SlidingStackedWidget.o SlidingStackedWidget.cpp

loadpages.o: loadpages.cpp loadpages.h \
		documentwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loadpages.o loadpages.cpp

filebrowser.o: filebrowser.cpp filebrowser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filebrowser.o filebrowser.cpp

moc_documentwidget.o: moc_documentwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_documentwidget.o moc_documentwidget.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

moc_SlidingStackedWidget.o: moc_SlidingStackedWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SlidingStackedWidget.o moc_SlidingStackedWidget.cpp

moc_loadpages.o: moc_loadpages.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loadpages.o moc_loadpages.cpp

moc_filebrowser.o: moc_filebrowser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filebrowser.o moc_filebrowser.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

